/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/UI/AppButton.vue')['default']
    AppDialog: typeof import('./src/components/UI/AppDialog.vue')['default']
    AppInput: typeof import('./src/components/UI/AppInput.vue')['default']
    AppSelect: typeof import('./src/components/UI/AppSelect.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    CardList: typeof import('./src/components/CardList.vue')['default']
    CartList: typeof import('./src/components/CartList.vue')['default']
    CartListItem: typeof import('./src/components/CartListItem.vue')['default']
    Category: typeof import('./src/components/Category.vue')['default']
    CategoryList: typeof import('./src/components/CategoryList.vue')['default']
    Crumbs: typeof import('./src/components/Crumbs.vue')['default']
    Drawer: typeof import('./src/components/Drawer.vue')['default']
    EmptyBlock: typeof import('./src/components/EmptyBlock.vue')['default']
    FavoriteList: typeof import('./src/components/FavoriteList.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HistoryOrders: typeof import('./src/components/history/HistoryOrders.vue')['default']
    InfoBlock: typeof import('./src/components/InfoBlock.vue')['default']
    InfoDelivery: typeof import('./src/components/history/InfoDelivery.vue')['default']
    InfoOrder: typeof import('./src/components/history/InfoOrder.vue')['default']
    InfoText: typeof import('./src/components/InfoText.vue')['default']
    ListOrders: typeof import('./src/components/history/ListOrders.vue')['default']
    Map: typeof import('./src/components/Map.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SliderCategory: typeof import('./src/components/SliderCategory.vue')['default']
    SliderOrder: typeof import('./src/components/SliderOrder.vue')['default']
    SliderProduct: typeof import('./src/components/SliderProduct.vue')['default']
    SliderTop: typeof import('./src/components/SliderTop.vue')['default']
    StepsOrder: typeof import('./src/components/history/StepsOrder.vue')['default']
    Tips: typeof import('./src/components/history/Tips.vue')['default']
  }
}
